/**
 * Islamic / Hijri Calendar Data for 2026 (1447–1448 AH) and 2027 (1448–1449 AH)
 * Based on Muslim Pro & standard global Hijri calculations
 */

export interface IslamicFestival {
  id: string;
  name: string;
  nameUrdu: string;
  nameHi: string;
  hijriDate: string;
  hijriMonth: string;
  gregorianDate2026: string;
  gregorianDate2027: string;
  day2026: string;
  day2027: string;
  monthIndex: number; // 1-12
  category: "holy_night" | "fasting" | "eid" | "hajj" | "special";
  categoryLabel: string;
  categoryColor: string;
  badgeBg: string;
  icon: string; // emoji/icon
  description: string;
  descriptionHi: string;
  descriptionHinglish: string;
  significance: string;
}

export const ISLAMIC_MONTHS = [
  { number: 1, name: "Muharram", urdu: "محرم الحرام", meaning: "Sacred Month" },
  { number: 2, name: "Safar", urdu: "صفر المظفر", meaning: "Month of Travel" },
  { number: 3, name: "Rabi' al-Awwal", urdu: "ربیع الاول", meaning: "Month of Prophet's Birth" },
  { number: 4, name: "Rabi' al-Thani", urdu: "ربیع الثانی / ربیع الآخر", meaning: "Month of Gyarvi Sharif" },
  { number: 5, name: "Jumada al-Awwal", urdu: "جمادی الاول", meaning: "First Month of Summer" },
  { number: 6, name: "Jumada al-Thani", urdu: "جمادی الثانی", meaning: "Second Month of Summer" },
  { number: 7, name: "Rajab", urdu: "رجب المرجب", meaning: "Sacred Month of Miraj" },
  { number: 8, name: "Sha'ban", urdu: "شعبان المعظم", meaning: "Month of Shab-e-Barat" },
  { number: 9, name: "Ramadan", urdu: "رمضان المبارک", meaning: "Holy Month of Fasting" },
  { number: 10, name: "Shawwal", urdu: "شوال المکرم", meaning: "Month of Eid al-Fitr" },
  { number: 11, name: "Dhul Qa'dah", urdu: "ذوالقعدۃ", meaning: "Sacred Month" },
  { number: 12, name: "Dhul Hijjah", urdu: "ذوالحجۃ", meaning: "Month of Hajj & Eid al-Adha" },
];

export const UPCOMING_FESTIVALS: IslamicFestival[] = [
  {
    id: "shab-e-miraj",
    name: "Isra and Mi'raj (Shab-e-Miraj)",
    nameUrdu: "شب معراج النبی ﷺ",
    nameHi: "शब-ए-मेराज (इसरा और मेराज)",
    hijriDate: "27 Rajab",
    hijriMonth: "Rajab",
    gregorianDate2026: "16 January 2026",
    gregorianDate2027: "5 January 2027",
    day2026: "Friday",
    day2027: "Tuesday",
    monthIndex: 1,
    category: "holy_night",
    categoryLabel: "Holy Night",
    categoryColor: "text-purple-700 bg-purple-100 border-purple-800",
    badgeBg: "bg-purple-600",
    icon: "🌌",
    description: "The miraculous night journey and ascension of Prophet Muhammad ﷺ through the heavens.",
    descriptionHi: "हज़रत मोहम्मद मुस्तफ़ा ﷺ का आसमानों पर नूरानी सफ़र और अल्लाह तआला का दीदार।",
    descriptionHinglish: "Nabi Kareem ﷺ ka aasmaano ka muqaddas safar aur Allah se mulaqat ki mubarak raat.",
    significance: "Gift of 5 Daily Prayers (Salah) bestowed upon the Muslim Ummah.",
  },
  {
    id: "shab-e-barat",
    name: "Shab-e-Barat (Mid-Sha'ban)",
    nameUrdu: "شب برات (لیلۃ البراءۃ)",
    nameHi: "शब-ए-बरात (मगफिरत की रात)",
    hijriDate: "15 Sha'ban",
    hijriMonth: "Sha'ban",
    gregorianDate2026: "3 February 2026",
    gregorianDate2027: "23 January 2027",
    day2026: "Tuesday",
    day2027: "Saturday",
    monthIndex: 2,
    category: "holy_night",
    categoryLabel: "Night of Forgiveness",
    categoryColor: "text-indigo-700 bg-indigo-100 border-indigo-800",
    badgeBg: "bg-indigo-600",
    icon: "✨",
    description: "The night of records, forgiveness, and divine mercy where fortunes for the coming year are finalized.",
    descriptionHi: "गुनाहों से मगफ़िरत, तौबा और अगले साल के रिज़्क और तक़दीर के फ़ैसलों की बरकत वाली रात।",
    descriptionHinglish: "Gunahon se tauba, maghfirat aur aane wale saal ki taqdeer tay hone ki muqaddas raat.",
    significance: "Special prayers, Quran recitation, and visiting the graves of loved ones (Ziyarat).",
  },
  {
    id: "ramadan-start",
    name: "Start of Ramadan (First Roza)",
    nameUrdu: "پہلا روزہ و آغاز رمضان المبارک",
    nameHi: "माहे रमज़ान शरीफ़ का पहला रोज़ा",
    hijriDate: "1 Ramadan",
    hijriMonth: "Ramadan",
    gregorianDate2026: "18 February 2026",
    gregorianDate2027: "8 February 2027",
    day2026: "Wednesday",
    day2027: "Monday",
    monthIndex: 2,
    category: "fasting",
    categoryLabel: "Holy Month of Fasting",
    categoryColor: "text-emerald-800 bg-emerald-100 border-emerald-800",
    badgeBg: "bg-emerald-600",
    icon: "🌙",
    description: "Beginning of the blessed month of fasting, Taraweeh prayers, charity, and Quranic revelation.",
    descriptionHi: "मुबारक महीने का आगाज़, रोज़े, तरावीह की नमाज़, और अवाम में चंदा व सदक़ात की बहार।",
    descriptionHinglish: "Barkat aur noor bhare maheene ka aaghaz, roze, taraweeh aur sadqa-e-jariya.",
    significance: "Fasting obligatory for every adult Muslim; gates of Paradise open.",
  },
  {
    id: "laylat-al-qadr",
    name: "Laylat al-Qadr (Night of Power)",
    nameUrdu: "شب قدر (لیلۃ القدر)",
    nameHi: "शब-ए-क़द्र (हज़ार महीनों से बेहतर रात)",
    hijriDate: "27 Ramadan",
    hijriMonth: "Ramadan",
    gregorianDate2026: "16 March 2026",
    gregorianDate2027: "6 March 2027",
    day2026: "Monday",
    day2027: "Saturday",
    monthIndex: 3,
    category: "holy_night",
    categoryLabel: "Night of Power",
    categoryColor: "text-amber-800 bg-amber-100 border-amber-800",
    badgeBg: "bg-amber-600",
    icon: "⭐",
    description: "The night better than a thousand months in which the Holy Quran was first revealed.",
    descriptionHi: "हज़ार महीनों से बेहतर रात जिसमें कुरआन मजीद का नुज़ूल हुआ। पूरी रात दुआ और इबादत।",
    descriptionHinglish: "Hazaar mahino se afzal raat jismein Quran-e-Pak ka nuzool hua.",
    significance: "Worship in this single night carries the reward of over 83 years of continuous devotion.",
  },
  {
    id: "eid-al-fitr",
    name: "Eid al-Fitr (Meethi Eid)",
    nameUrdu: "عید الفطر المبارک",
    nameHi: "ईद-उल-फ़ित्र (मीठी ईद)",
    hijriDate: "1 Shawwal",
    hijriMonth: "Shawwal",
    gregorianDate2026: "20 March 2026",
    gregorianDate2027: "10 March 2027",
    day2026: "Friday",
    day2027: "Wednesday",
    monthIndex: 3,
    category: "eid",
    categoryLabel: "Eid Celebration",
    categoryColor: "text-blue-800 bg-blue-100 border-blue-800",
    badgeBg: "bg-[#252BFF]",
    icon: "🕌",
    description: "Joyous celebration marking the completion of Ramadan fasting with community prayers and charity (Fitra).",
    descriptionHi: "रमज़ान के रोज़े मुकम्मल होने की खुशी, ईदगाह में नमाज़, गले मिलना और शीर-खुरमा की मिठास।",
    descriptionHinglish: "Roze mukammal hone ki shandar khushi, Eidgah mein namaz aur sabhi apno ko mubarakbaad.",
    significance: "Special congregational Eid prayer in Quadri Jama Masjid, Deoria Baradih.",
  },
  {
    id: "day-of-arafah",
    name: "Day of Arafah (Hajj Day)",
    nameUrdu: "یوم عرفہ (وقوف عرفات)",
    nameHi: "यौम-ए-अरफ़ा (हज का दिन)",
    hijriDate: "9 Dhul Hijjah",
    hijriMonth: "Dhul Hijjah",
    gregorianDate2026: "26 May 2026",
    gregorianDate2027: "15 May 2027",
    day2026: "Tuesday",
    day2027: "Saturday",
    monthIndex: 5,
    category: "hajj",
    categoryLabel: "Pinnacle of Hajj",
    categoryColor: "text-rose-800 bg-rose-100 border-rose-800",
    badgeBg: "bg-rose-600",
    icon: "🕋",
    description: "The culminating day of the Hajj pilgrimage where pilgrims gather on the plain of Mount Arafat.",
    descriptionHi: "हज का सबसे अज़ीम दिन, मैदान-ए-अरफ़ात में हाजियों का इज्तिमा। गैर-हाजियों के लिए रोज़ा सुन्नत।",
    descriptionHinglish: "Hajj ka sabse azeem din. Is din ka roza pichhle aur agle saal ke gunah maaf karata hai.",
    significance: "Fasting on this day expiates sins of the previous year and the coming year.",
  },
  {
    id: "eid-al-adha",
    name: "Eid al-Adha (Bakrid)",
    nameUrdu: "عید الاضحیٰ (بقرعید)",
    nameHi: "ईद-उल-अज़हा (बक़रीद / क़ुर्बानी)",
    hijriDate: "10 Dhul Hijjah",
    hijriMonth: "Dhul Hijjah",
    gregorianDate2026: "27 May 2026",
    gregorianDate2027: "16 May 2027",
    day2026: "Wednesday",
    day2027: "Sunday",
    monthIndex: 5,
    category: "eid",
    categoryLabel: "Feast of Sacrifice",
    categoryColor: "text-green-800 bg-green-100 border-green-800",
    badgeBg: "bg-[#00875A]",
    icon: "🐑",
    description: "Commemorating Prophet Ibrahim's (AS) devotion with congregational prayer and animal sacrifice (Qurbani).",
    descriptionHi: "हज़रत इब्राहिम अलैहिस्सलाम की अज़ीम क़ुर्बानी की याद, नमाज़ और ग़रीबों में गोश्त की तक़सीम।",
    descriptionHinglish: "Hazrat Ibrahim (AS) ki sunnat, qurbani ka azeem jazba aur zarooratmand tak madad.",
    significance: "Major three-day festival of sacrifice and community charity.",
  },
  {
    id: "islamic-new-year",
    name: "Islamic New Year (1448 AH)",
    nameUrdu: "نیا اسلامی سال (یکم محرم الحرام)",
    nameHi: "नया इस्लामी हिजरी साल (1 मुहर्रम)",
    hijriDate: "1 Muharram",
    hijriMonth: "Muharram",
    gregorianDate2026: "17 June 2026",
    gregorianDate2027: "6 June 2027",
    day2026: "Wednesday",
    day2027: "Sunday",
    monthIndex: 6,
    category: "special",
    categoryLabel: "New Hijri Year",
    categoryColor: "text-teal-800 bg-teal-100 border-teal-800",
    badgeBg: "bg-teal-600",
    icon: "🗓️",
    description: "The first day of the Islamic Hijri calendar, marking the historic Hijrah from Mecca to Medina.",
    descriptionHi: "मक्का शरीफ़ से मदीना मुनव्वरा की तारीखी हिजरत की याद में नया हिजरी साल 1448 का आगाज़।",
    descriptionHinglish: "Naye Islami saal ka aaghaz, Nabi Kareem ﷺ ki Hijrat-e-Madinah ki yaad.",
    significance: "Begins the sacred month of Muharram.",
  },
  {
    id: "ashura",
    name: "Day of Ashura (10 Muharram)",
    nameUrdu: "یوم عاشورہ (شہادت امام حسین رض)",
    nameHi: "यौम-ए-आशूरा (10 मुहर्रम)",
    hijriDate: "10 Muharram",
    hijriMonth: "Muharram",
    gregorianDate2026: "26 June 2026",
    gregorianDate2027: "15 June 2027",
    day2026: "Friday",
    day2027: "Tuesday",
    monthIndex: 6,
    category: "holy_night",
    categoryLabel: "Sacred Day",
    categoryColor: "text-red-800 bg-red-100 border-red-800",
    badgeBg: "bg-[#FF3864]",
    icon: "🕊️",
    description: "A day of profound fasting and remembrance of the martyrdom of Imam Hussain (RA) at Karbala.",
    descriptionHi: "हज़रत इमाम हुसैन रज़ि० और कर्बला के शहीदों की अज़ीम शहादत की याद और सुन्नत रोज़ा।",
    descriptionHinglish: "Imam Hussain (RA) aur Karbala ke shohada ki yaad, sabr aur roza rakhne ka din.",
    significance: "Sunnah fasting on the 9th and 10th of Muharram.",
  },
  {
    id: "mawlid-an-nabi",
    name: "Mawlid an-Nabi (Eid Milad-un-Nabi)",
    nameUrdu: "جشن عید میلاد النبی ﷺ",
    nameHi: "ईद मिलाद-उन-नबी ﷺ (12 रबीउल अव्वल)",
    hijriDate: "12 Rabi' al-Awwal",
    hijriMonth: "Rabi' al-Awwal",
    gregorianDate2026: "25 August 2026",
    gregorianDate2027: "14 August 2027",
    day2026: "Tuesday",
    day2027: "Saturday",
    monthIndex: 8,
    category: "special",
    categoryLabel: "Prophet's Birthday",
    categoryColor: "text-emerald-800 bg-emerald-100 border-emerald-800",
    badgeBg: "bg-[#0B0906]",
    icon: "🕌",
    description: "Joyous celebration of the birth of the beloved Prophet Muhammad ﷺ (Rahmatul-lil-Alameen).",
    descriptionHi: "सारे जहां के लिए रहमत बनकर आए नबी-ए-पाक हज़रत मोहम्मद ﷺ के विलादत की मुबारक खुशी।",
    descriptionHinglish: "Rahmatul-lil-Alameen Nabi Kareem ﷺ ki wiladat-e-ba-sa'adat ka jashn.",
    significance: "Grand gatherings, Naat recitations, lights, and food distribution across Deoria Baradih.",
  },
  {
    id: "gyarvi-sharif",
    name: "Gyarvi Sharif (Ghaus-e-Azam RA)",
    nameUrdu: "گیارھویں شریف (حضرت شیخ عبدالقادر جیلانیؒ)",
    nameHi: "ग्यारहवीं शरीफ़ (हज़रत ग़ौस-ए-आज़म रह०)",
    hijriDate: "11 Rabi' al-Thani",
    hijriMonth: "Rabi' al-Thani",
    gregorianDate2026: "23 September 2026",
    gregorianDate2027: "12 September 2027",
    day2026: "Wednesday",
    day2027: "Sunday",
    monthIndex: 9,
    category: "special",
    categoryLabel: "Quadri Heritage Event",
    categoryColor: "text-amber-900 bg-amber-100 border-amber-900",
    badgeBg: "bg-[#C8FF19] text-[#0B0906]",
    icon: "👑",
    description: "Commemoration of the leader of Awliya, Hazrat Sheikh Abdul Qadir Jilani (RA) - patron saint of Quadri Jama Masjid.",
    descriptionHi: "पीराने पीर दस्तगीर हज़रत शैख़ अब्दुल क़ादिर जीलानी रह० का मुबारक उर्स व नियाज़ (कुआदरी मस्जिद की ख़ास निस्बत)।",
    descriptionHinglish: "Quadri Jama Masjid ki shaan: Ghaus-e-Azam Dastageer (RA) ki Gyarvi Sharif ki mehfil aur langar.",
    significance: "Special annual gathering and community banquet at Quadri Jama Masjid Deoria.",
  },
];
